# DON'T MODIFY Spawn Location
locations:
  spawn:

# SCOREBOARD Settings and title
scoreboard:
  ticks: 20

# Menus Hubs Selector
MENU:
  HUBS:
    HUB-1:
      MATERIAL: "EYE_OF_ENDER"
    HUB-2:
      MATERIAL: "ENDER_PEARL"