#####################################################
# SCOREBOARD Settings and title
SCOREBOARD:
  TICKS: 20
  TITLE: "&b&lHUB &8| &7#1"

#####################################################
# On join message title
ONJOIN:
  TITLE: "&b&lNASGAR &7| &fHUB &7#1"