main: online.nasgar.hubcore.hubcore.HubCore
name: HubCore
version: ${project.version}

api-version: 1.8
api: ${project.java.version}

authors: [ NasgarNetwork Development Team]
description: The Nasgar Network HubCore

softdepend: [ PlaceholderAPI ]

commands:
  setspawn:
  hubcore:
    aliases:
      - hc
  fly:
    aliases:
      - volar