main: online.nasgar.hubcore.hubcore.HubCore
name: HubCore
version: '${project.version}'

api-version: 1.8
api: ${project.java.version}

authors: [ NasgarNetwork, Aitooor ]
description: The Nasgar Network HubCore

commands:
   setspawn:
   fly:
   flytimer:
   hubcore:
     aliases:
       - hc