main: online.nasgar.hubcore.hubcore.HubCore
name: HubCore
version: ${project.version}
description: Nasgar Network HubCore 1.8
authors: [ NasgarNetwork Development Team]
api-version: 1.8

softdepend: [ PlaceholderAPI ]

commands:
  hubcore:
    aliases:
      - hc
  menus:
    aliases:
      - menu
