main: online.nasgar.hubcore.hubcore.HubCore
name: HubCore
version: '1.0.1'

api-version: 1.8
api: ${project.java.version}

authors: [ NasgarNetwork, Aitooor ]
description: The Nasgar Network HubCore

commands:
  setspawn:
  fly:
    aliases:
      - volar
  flytimer: